### ISSUE TITLE
Husqvarna account update

### ISSUE THREAD

**Issue by nicdive** [chrisz/pyhusmow#7]
Hi,

I was using your script to command my automower with my home automation system. It worked well till today. I received an account update information from husqvarna and now the script is in error. It needs an update or is it a problem on my side?

Anyway, thanks for the work !

**Comment by ghost** [comment]
Hi nicdive, chrisz,
I was suffering from the very same yesterday - Husqvarna account update (had to reset the Password and finally freshly couple the mower to my Profile). I am not sure if that is related to the usage of your script (connecting to their Servers from outside their app) or if this is a General issue with Husqvarna.

**Comment by chrisz** [comment]
Hi @nicdive , @eurohopper , Husqvarna have changed a lot of things on Automower Connect and they have changed the API to control the automower remotely :-( . I bring my automower for service some days ago so I can't check if there is a lot of work to repair pyhusmow now.

**Comment by gotgot04** [comment]
Same issue here. Tell us if we can do anything to help you.

**Comment by chrisz** [comment]
Hi @nicdive , @eurohopper , @gotgot04 , I made some fixes to repair pyhusmow but, without my mower, I can't check if it's ok. If you want, you can test the updated script from my branch "2017" : https://github.com/chrisz/pyhusmow/blob/2017/husmow.py

**Comment by gotgot04** [comment]
Hi Chrisz,

Thank you very much 

I Get this error :
Traceback (most recent call last):
  File "/var/www/husmow/husmow.py", line 6, in <module>
    from configparser import configparser
ImportError: No module named configparser

**Comment by gotgot04** [comment]
Okay, solved installing python3.4 and python3-requests.
Data seems to be formatted differently but seems to work

**Comment by gotgot04** [comment]
Just a stupid question : How to disable logging?

**Comment by nicdive** [comment]
Hi, 
Works for me, thanks a lot!

**Comment by chrisz** [comment]
You can use the option --log-level ERROR to disable log level info but, currently, you can't disable all logs.

Thanks for your tests. I merged my branch in master.

**Comment by ArthurHeller** [comment]
After installing all dependencies on raspbian I receive;
python3 husmow.py control STOP
Logger configured
request() got an unexpected keyword argument 'json'
[ERROR] Retrying to send the command 2
request() got an unexpected keyword argument 'json'
[ERROR] Retrying to send the command 1
[ERROR] Failed to send the command
Done

It might be related to request(), only version python3-requests_0.12.1-1+deb7u1_all.deb installed in recent raspbian, but manually upgrading is not working:
 pip-3.2 install --upgrade requests
Downloading/unpacking requests from https://pypi.python.org/packages/2c/b5/2b6e8ef8dd18203b6399e9f28c7d54f6de7b7549853fe36d575bd31e29a7/requests-2.18.1.tar.gz#md5=40f723ed01dddeaf990d0609d073f021
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/requests/setup.py", line 55, in <module>
        exec(f.read(), about)
      File "<string>", line 14
        __cake__ = u'\u2728 \U0001f370 \u2728'
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/requests/setup.py", line 55, in <module>

    exec(f.read(), about)

  File "<string>", line 14

    __cake__ = u'\u2728 \U0001f370 \u2728'

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/requests

Whats can I do?
Thank you!

**Comment by chrisz** [comment]
Hi @ArthurHeller ,

The simple way to install pyhusmow on raspbian is with virtualenv to install the dependencies.

I had explanations in the README https://github.com/chrisz/pyhusmow/blob/master/README.md .

I hope this will help you

Chris

**Comment by ArthurHeller** [comment]
Thank you for your reply!

 

Here is what I did (command pip3 not existing):

 

pip-3.2 install virtualenv

Downloading/unpacking virtualenv

  Downloading virtualenv-15.1.0.tar.gz (1.9Mb): 1.9Mb downloaded

  Running setup.py egg_info for package virtualenv

 

    warning: no previously-included files matching '*' found under directory 'docs/_templates'

    warning: no previously-included files matching '*' found under directory 'docs/_build'

Installing collected packages: virtualenv

  Running setup.py install for virtualenv

 

    warning: no previously-included files matching '*' found under directory 'docs/_templates'

    warning: no previously-included files matching '*' found under directory 'docs/_build'

    Installing virtualenv script to /usr/local/bin

Successfully installed virtualenv

Cleaning up...

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/pi/husmow_venv/bin/python3

Also creating executable in /home/pi/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/pi/husmow_venv/bin/python3 - setuptools pip wheel:

  Traceback (most recent call last):

  File "<stdin>", line 7, in <module>

  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 21, in <module>

  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 66, in <module>

  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/models.py", line 856

    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)

                                                      ^

SyntaxError: invalid syntax

----------------------------------------

...Installing setuptools, pip, wheel...done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 2328, in <module>

    main()

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 713, in main

    symlink=options.symlink)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 945, in create_environment

    download=download,

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 901, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 797, in call_subprocess

    % (cmd_desc, proc.returncode))

OSError: Command /home/pi/husmow_venv/bin/python3 - setuptools pip wheel failed with error code 1

 

Arthur

 

Von: Christophe Carré [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Juni 2017 20:10
An: chrisz/pyhusmow <pyhusmow@noreply.github.com>
Cc: ArthurHeller <arthur.heller@utanet.at>; Mention <mention@noreply.github.com>
Betreff: Re: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Hi @ArthurHeller <https://github.com/arthurheller>  ,

The simple way to install pyhusmow on raspbian is with virtualenv to install the dependencies.

I had explanations in the README https://github.com/chrisz/pyhusmow/blob/master/README.md .

I hope this will help you

Chris

**Comment by chrisz** [comment]
Have you executed these commands with sudo ? If yes, maybe you have overwritten some system packages which can cause these kind of problems.

I searched in my history on raspbian. To install virtualenv, I installed these two pacckages :

sudo apt install python3-virtualenv
sudo apt install virtualenv

**Comment by ArthurHeller** [comment]
Yes, I did it with root, now retried with non root, same problem.

It’s a unicode problem, just tried to remove the “u” in front of the string.

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/software/husmow_venv/bin/python3

Also creating executable in /home/software/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/software/husmow_venv/bin/python3 - setuptools pip wheel:

  /usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

 

So virtualenv ist not supported for python3 which is needed by husmov..

 

Thank you,

Arthur

 

Von: Christophe Carré [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Juni 2017 22:18
An: chrisz/pyhusmow <pyhusmow@noreply.github.com>
Cc: ArthurHeller <arthur.heller@utanet.at>; Mention <mention@noreply.github.com>
Betreff: Re: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Have you executed these commands with sudo ? If yes, maybe you have overwritten some system packages which can cause these kind of problems.

I searched in my history on raspbian. To install virtualenv, I installed these two pacckages :

sudo apt install python3-virtualenv
sudo apt install virtualenv

**Comment by ArthurHeller** [comment]
After removing all the u characters marking unicode strings in pip-9.0.1-py2.py3-none-any.whl I receive:

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/software/husmow_venv/bin/python3

Also creating executable in /home/software/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/software/husmow_venv/bin/python3 - setuptools pip wheel:

  Collecting setuptools

  Downloading setuptools-30.1.0-py2.py3-none-any.whl (472kB)

Collecting pip

/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.3

----------------------------------------

...Installing setuptools, pip, wheel...done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 2328, in <module>

    main()

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 713, in main

    symlink=options.symlink)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 945, in create_environment

    download=download,

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 901, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 797, in call_subprocess

    % (cmd_desc, proc.returncode))

OSError: Command /home/software/husmow_venv/bin/python3 - setuptools pip wheel failed with error code 1

 

Thank you,

Arthur

 

Von: Arthur Heller [mailto:arthur.heller@utanet.at] 
Gesendet: Donnerstag, 22. Juni 2017 08:48
An: 'chrisz/pyhusmow' <reply@reply.github.com>
Betreff: AW: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Yes, I did it with root, now retried with non root, same problem.

It’s a unicode problem, just tried to remove the “u” in front of the string.

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/software/husmow_venv/bin/python3

Also creating executable in /home/software/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/software/husmow_venv/bin/python3 - setuptools pip wheel:

  /usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

 

So virtualenv ist not supported for python3 which is needed by husmov..

 

Thank you,

Arthur

 

Von: Christophe Carré [ <mailto:notifications@github.com> mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Juni 2017 22:18
An: chrisz/pyhusmow < <mailto:pyhusmow@noreply.github.com> pyhusmow@noreply.github.com>
Cc: ArthurHeller < <mailto:arthur.heller@utanet.at> arthur.heller@utanet.at>; Mention < <mailto:mention@noreply.github.com> mention@noreply.github.com>
Betreff: Re: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Have you executed these commands with sudo ? If yes, maybe you have overwritten some system packages which can cause these kind of problems.

I searched in my history on raspbian. To install virtualenv, I installed these two pacckages :

sudo apt install python3-virtualenv
sudo apt install virtualenv

**Comment by ArthurHeller** [comment]
Managed to run

virtualenv -p python3 –no-pip husmow_venv

 

successfully but now, of course, have problems with installing python-dateutil

because pip is not available.

So I tried to install it the old way – curl and ..setup.py install

but received:

 

./husmow_venv/bin/python3 setup.py install

 

Traceback (most recent call last):

  File "setup.py", line 7, in <module>

    from setuptools import setup

  File "/home/software/husmow_venv/lib/python3.2/site-packages/setuptools/__init__.py", line 10, in <module>

    from setuptools.extern.six.moves import filter, filterfalse, map

  File "/home/software/husmow_venv/lib/python3.2/site-packages/setuptools/extern/__init__.py", line 1, in <module>

    from pkg_resources.extern import VendorImporter

  File "/home/software/husmow_venv/lib/python3.2/site-packages/pkg_resources/__init__.py", line 78, in <module>

    raise RuntimeError("Python 3.3 or later is required")

RuntimeError: Python 3.3 or later is required

 

Which is strange

 

Arthur

 

Von: Arthur Heller [mailto:arthur.heller@utanet.at] 
Gesendet: Donnerstag, 22. Juni 2017 09:06
An: 'chrisz/pyhusmow' <reply@reply.github.com>
Betreff: AW: [chrisz/pyhusmow] Husqvarna account update (#7)

 

After removing all the u characters marking unicode strings in pip-9.0.1-py2.py3-none-any.whl I receive:

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/software/husmow_venv/bin/python3

Also creating executable in /home/software/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/software/husmow_venv/bin/python3 - setuptools pip wheel:

  Collecting setuptools

  Downloading setuptools-30.1.0-py2.py3-none-any.whl (472kB)

Collecting pip

/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.3

----------------------------------------

...Installing setuptools, pip, wheel...done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 2328, in <module>

    main()

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 713, in main

    symlink=options.symlink)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 945, in create_environment

    download=download,

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 901, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)

  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 797, in call_subprocess

    % (cmd_desc, proc.returncode))

OSError: Command /home/software/husmow_venv/bin/python3 - setuptools pip wheel failed with error code 1

 

Thank you,

Arthur

 

Von: Arthur Heller [mailto:arthur.heller@utanet.at] 
Gesendet: Donnerstag, 22. Juni 2017 08:48
An: 'chrisz/pyhusmow' <reply@reply.github.com>
Betreff: AW: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Yes, I did it with root, now retried with non root, same problem.

It’s a unicode problem, just tried to remove the “u” in front of the string.

 

virtualenv -p python3 husmow_venv

Running virtualenv with interpreter /usr/bin/python3

New python executable in /home/software/husmow_venv/bin/python3

Also creating executable in /home/software/husmow_venv/bin/python

Installing setuptools, pip, wheel...

  Complete output from command /home/software/husmow_venv/bin/python3 - setuptools pip wheel:

  /usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

 

So virtualenv ist not supported for python3 which is needed by husmov..

 

Thank you,

Arthur

 

Von: Christophe Carré [ <mailto:notifications@github.com> mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Juni 2017 22:18
An: chrisz/pyhusmow < <mailto:pyhusmow@noreply.github.com> pyhusmow@noreply.github.com>
Cc: ArthurHeller < <mailto:arthur.heller@utanet.at> arthur.heller@utanet.at>; Mention < <mailto:mention@noreply.github.com> mention@noreply.github.com>
Betreff: Re: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Have you executed these commands with sudo ? If yes, maybe you have overwritten some system packages which can cause these kind of problems.

I searched in my history on raspbian. To install virtualenv, I installed these two pacckages :

sudo apt install python3-virtualenv
sudo apt install virtualenv

**Comment by chrisz** [comment]
Python 3.2 ? Do you use an old version of raspbian ? With raspbian 8, my version of python is 3.4.2.

It is possible you can't run pyhusmow with python version < 3.3.

**Comment by ArthurHeller** [comment]
You are right. Installed a new raspbian on another raspi and everything workes as it should.

Thank you for your great work!

 

Arthur

 

Von: Christophe Carré [mailto:notifications@github.com] 
Gesendet: Donnerstag, 22. Juni 2017 21:12
An: chrisz/pyhusmow <pyhusmow@noreply.github.com>
Cc: ArthurHeller <arthur.heller@utanet.at>; Mention <mention@noreply.github.com>
Betreff: Re: [chrisz/pyhusmow] Husqvarna account update (#7)

 

Python 3.2 ? Do you use an old version of raspbian ? With raspbian 8, my version of python is 3.4.2.

It is possible you can't run pyhusmow with python version < 3.3.

**Comment by arniworx** [comment]
hi!
thank you very much for this very helpful tool!
can you please make the output of the command-line version the same as the web output?
in the command-line version the output is in 'single' quotes and boolean values are mixed case like "True".
keys and values in "double" quotes are parseable by php's json_decode as well as boolean values in lowercase letters.
thank you
arni
